language: go
go:
    - 1.x
    - "1.8"
    - "1.9"
    - 1.10.x
before_install:
    - go get github.com/mattn/goveralls
script:
    - go test -v ./...
    - go test -race -coverprofile=coverage.txt -covermode=atomic
    - $GOPATH/bin/goveralls -service=travis-ci
dd:
    secure: eKUaA6uIzAFkiFGEQCDpzu3zdA8KTK3T3T+Y7IFtO/AnK2AlGBlGSqQvrG/1tsp2MigClbnc1UpdlqD8H3P4VxOOUXu9zEASyX0mEi28svtCtPx+qv0xIkce+sGj2kvk0QwL4a3YgFMm8e2gACWpdSE8jHd3zCGBVKC7ktPTeINryDyJEu9QU5LBzHt/tsOj6gu7rK8AwqzVBIRWHNWH4ZL8AWaeMhLBONSnpkstPGDWTh8p3B0YLIuFFss55zFzR11M13jX2lS65qo75EfHcNHz9L0oZ1JGIMTDRu4Oc8Wi0oW0gdyJrLgUvCvQVsQ9k8bjlxpy9opBsPHf+WhMYR/qjMBBecWLcOlyC2/6G51BtfsaI7hlITJiI8go2vZvek1aBzfKJSeN6gXN7ymKBQs5J2tILRk24T2BskSxZwE1LlJYzNpdCfyEd7642frRwNzVkMEaAoMYDaQlcJPdAB/kNJorfj4PSAmlVVq89TKUcgdIhKZ+UZexflWoroIJvW+VjSuf3SRC44M1zOVTwUgn7/FWGtVVitpBfxi+ZxVCwqPQqBYTwtqKFwF4hOJXnFGjSqtf/FIUUz1wlGNLWIwhmxTQyH+h4THl4WJtdBbiHFU81kphudfdmbGayXmashGyKQNmPuCeRBnAdOsJC/ef1eTAjzullFM6rKflz1A=
after_success:
    - bash <(curl -s https://codecov.io/bash)
